In [1]:
import torch

C:\Users\amirr\AppData\Roaming\Python\Python38\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
x = torch.rand(3, 3, requires_grad=True)
x

tensor([[0.9086, 0.2819, 0.3977],
        [0.2706, 0.2237, 0.5631],
        [0.8484, 0.2819, 0.5571]], requires_grad=True)

In [5]:
y = x + 2

In [7]:
y

tensor([[2.9086, 2.2819, 2.3977],
        [2.2706, 2.2237, 2.5631],
        [2.8484, 2.2819, 2.5571]], grad_fn=<AddBackward0>)

In [8]:
z = y * y * 2
z

tensor([[16.9203, 10.4141, 11.4979],
        [10.3114,  9.8895, 13.1394],
        [16.2270, 10.4139, 13.0779]], grad_fn=<MulBackward0>)

In [9]:
m = z.mean()
m

tensor(12.4324, grad_fn=<MeanBackward0>)

In [10]:
m.backward()

In [13]:
x.grad

tensor([[1.2927, 1.0142, 1.0656],
        [1.0092, 0.9883, 1.1392],
        [1.2660, 1.0142, 1.1365]])

In [19]:
x1 = torch.rand(2, 2, requires_grad=True)
x1

tensor([[0.0227, 0.8076],
        [0.1830, 0.6825]], requires_grad=True)

In [20]:
y1 = x1 * x1
y1

tensor([[5.1653e-04, 6.5223e-01],
        [3.3472e-02, 4.6574e-01]], grad_fn=<MulBackward0>)

In [22]:
x2 = torch.rand(2, 1, requires_grad=True)
x2

tensor([[0.9896],
        [0.6690]], requires_grad=True)

In [25]:
y2 = torch.matmul(x2.T, x2)
y2

tensor([[1.4268]], grad_fn=<MmBackward0>)

In [26]:
y2.backward()

In [27]:
x2.grad

tensor([[1.9791],
        [1.3380]])

In [49]:
2 * x2

tensor([[1.9791],
        [1.3380]], grad_fn=<MulBackward0>)

In [50]:
w = torch.tensor(0, requires_grad=True, dtype=torch.float32)
b = torch.tensor(0, requires_grad=True, dtype=torch.float32)
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([3, 5, 7, 9], dtype=torch.float32)

In [51]:
def forward(x):
    return w * x + b

def loss(y, yp):
    return ((y - yp) ** 2).mean()

In [56]:
for i in range(100000):
    yp = forward(X)
    l = loss(y, yp)
    l.backward()
    with torch.no_grad():
        w -=  0.01 * w.grad
        b -= 0.01 * b.grad
    w.grad.zero_()
    b.grad.zero_()

In [58]:
w.item(), b.item()

(2.000007390975952, 0.9999802112579346)

In [59]:
l

tensor(6.7757e-11, grad_fn=<MeanBackward0>)