In [1]:
import torch

C:\Users\amirr\AppData\Roaming\Python\Python38\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
x = torch.empty(2, 3)
x

tensor([[3., 2., 1.],
        [0., 1., 2.]])

In [9]:
x1 = torch.rand(2, 3)
x1

tensor([[0.1193, 0.6421, 0.6511],
        [0.5589, 0.5536, 0.3338]])

In [11]:
z = torch.zeros(2, 2)
z

tensor([[0., 0.],
        [0., 0.]])

In [22]:
o = torch.ones(3, 3, dtype=torch.int)
o, o.dtype, o.shape[0]

(tensor([[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]], dtype=torch.int32),
 torch.int32,
 3)

In [24]:
tens = torch.tensor(
    [[2, 4],
    [3, 5]])
tens

tensor([[2, 4],
        [3, 5]])

In [28]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
x, y

(tensor([[0.5815, 0.5394],
         [0.1401, 0.6821]]),
 tensor([[0.2926, 0.9248],
         [0.3967, 0.8854]]))

In [29]:
x + y

tensor([[0.8741, 1.4642],
        [0.5368, 1.5675]])

In [30]:
x * y

tensor([[0.1702, 0.4988],
        [0.0556, 0.6039]])

In [35]:
x[0, 0] * y[0, 0]

tensor(0.1702)

In [38]:
xaddy = torch.add(x, y)
xaddy, x.add_(y)

(tensor([[0.8741, 1.4642],
         [0.5368, 1.5675]]),
 tensor([[0.8741, 1.4642],
         [0.5368, 1.5675]]))

In [40]:
xy = torch.mul(x, y)
xy

tensor([[0.2558, 1.3541],
        [0.2129, 1.3878]])

In [41]:
x

tensor([[0.8741, 1.4642],
        [0.5368, 1.5675]])

In [42]:
y

tensor([[0.2926, 0.9248],
        [0.3967, 0.8854]])

In [43]:
0.2926 * 0.8741

0.25576166

In [44]:
xy[0, 0].item()

0.25578516721725464

In [46]:
rnd = torch.rand(6, 6)
rnd

tensor([[0.1982, 0.4488, 0.1021, 0.1502, 0.9616, 0.2484],
        [0.4310, 0.9111, 0.6052, 0.3504, 0.3682, 0.6161],
        [0.9777, 0.4283, 0.2177, 0.6119, 0.1874, 0.6412],
        [0.3542, 0.4733, 0.0951, 0.4588, 0.4628, 0.6603],
        [0.1993, 0.5892, 0.3301, 0.3276, 0.3564, 0.1629],
        [0.3238, 0.4695, 0.5038, 0.8908, 0.5950, 0.0520]])

In [47]:
rnd.view(-1, 4)

tensor([[0.1982, 0.4488, 0.1021, 0.1502],
        [0.9616, 0.2484, 0.4310, 0.9111],
        [0.6052, 0.3504, 0.3682, 0.6161],
        [0.9777, 0.4283, 0.2177, 0.6119],
        [0.1874, 0.6412, 0.3542, 0.4733],
        [0.0951, 0.4588, 0.4628, 0.6603],
        [0.1993, 0.5892, 0.3301, 0.3276],
        [0.3564, 0.1629, 0.3238, 0.4695],
        [0.5038, 0.8908, 0.5950, 0.0520]])

In [48]:
rnd

tensor([[0.1982, 0.4488, 0.1021, 0.1502, 0.9616, 0.2484],
        [0.4310, 0.9111, 0.6052, 0.3504, 0.3682, 0.6161],
        [0.9777, 0.4283, 0.2177, 0.6119, 0.1874, 0.6412],
        [0.3542, 0.4733, 0.0951, 0.4588, 0.4628, 0.6603],
        [0.1993, 0.5892, 0.3301, 0.3276, 0.3564, 0.1629],
        [0.3238, 0.4695, 0.5038, 0.8908, 0.5950, 0.0520]])

In [50]:
rnd.view(-1)

tensor([0.1982, 0.4488, 0.1021, 0.1502, 0.9616, 0.2484, 0.4310, 0.9111, 0.6052,
        0.3504, 0.3682, 0.6161, 0.9777, 0.4283, 0.2177, 0.6119, 0.1874, 0.6412,
        0.3542, 0.4733, 0.0951, 0.4588, 0.4628, 0.6603, 0.1993, 0.5892, 0.3301,
        0.3276, 0.3564, 0.1629, 0.3238, 0.4695, 0.5038, 0.8908, 0.5950, 0.0520])

In [51]:
rnd.flatten()

tensor([0.1982, 0.4488, 0.1021, 0.1502, 0.9616, 0.2484, 0.4310, 0.9111, 0.6052,
        0.3504, 0.3682, 0.6161, 0.9777, 0.4283, 0.2177, 0.6119, 0.1874, 0.6412,
        0.3542, 0.4733, 0.0951, 0.4588, 0.4628, 0.6603, 0.1993, 0.5892, 0.3301,
        0.3276, 0.3564, 0.1629, 0.3238, 0.4695, 0.5038, 0.8908, 0.5950, 0.0520])

In [54]:
n_rnd = rnd.numpy()

In [55]:
rnd[0, 0] = 2

In [56]:
rnd

tensor([[2.0000, 0.4488, 0.1021, 0.1502, 0.9616, 0.2484],
        [0.4310, 0.9111, 0.6052, 0.3504, 0.3682, 0.6161],
        [0.9777, 0.4283, 0.2177, 0.6119, 0.1874, 0.6412],
        [0.3542, 0.4733, 0.0951, 0.4588, 0.4628, 0.6603],
        [0.1993, 0.5892, 0.3301, 0.3276, 0.3564, 0.1629],
        [0.3238, 0.4695, 0.5038, 0.8908, 0.5950, 0.0520]])

In [57]:
n_rnd

array([[2.        , 0.4487772 , 0.10206491, 0.15015304, 0.96156776,
        0.24842095],
       [0.43098795, 0.91110605, 0.60515475, 0.3503508 , 0.36816692,
        0.6161111 ],
       [0.9776959 , 0.4283011 , 0.21774185, 0.6118608 , 0.1874125 ,
        0.641195  ],
       [0.35416007, 0.4732805 , 0.09508246, 0.45879507, 0.46277344,
        0.66027147],
       [0.19927734, 0.5891612 , 0.33011782, 0.32758188, 0.35636955,
        0.16287476],
       [0.32384795, 0.4695217 , 0.50377816, 0.8908276 , 0.5950316 ,
        0.05198294]], dtype=float32)

In [58]:
import numpy as np
a = np.zeros((3, 3))
b = torch.from_numpy(a)
a += 1

In [59]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [60]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
torch.cuda.is_available()

False