In [1]:
import torch
import torch.nn as nn

C:\Users\amirr\AppData\Roaming\Python\Python38\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([3, 5, 7, 9], dtype=torch.float32)

In [3]:
w = torch.tensor(0, requires_grad=True, dtype=torch.float32)
b = torch.tensor(0, requires_grad=True, dtype=torch.float32)

In [4]:
loss = nn.MSELoss()
optimizer = torch.optim.SGD([w, b], lr=0.01)

In [6]:
for i in range(10000):
    yp = w * X + b
    l = loss(y, yp)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()

In [9]:
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
y = torch.tensor([[3], [5], [7], [9]], dtype=torch.float32)

In [12]:
loss = nn.MSELoss()
model = nn.Linear(1, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [13]:
for i in range(10000):
    yp = model(X)
    l = loss(y, yp)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()

In [15]:
[w, b] = model.parameters()

In [16]:
w

Parameter containing:
tensor([[2.0000]], requires_grad=True)

In [17]:
b

Parameter containing:
tensor([1.0000], requires_grad=True)

In [21]:
loss = nn.MSELoss()
class LR(nn.Module):
    def __init__(self, i, o):
        super(LR, self).__init__()
        self.lin = nn.Linear(i, o)
    def forward(self, x):
        return self.lin(x)
model = LR(1, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [22]:
for i in range(10000):
    yp = model(X)
    l = loss(y, yp)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()

In [23]:
[w, b] = model.parameters()

In [24]:
w

Parameter containing:
tensor([[2.0000]], requires_grad=True)

In [25]:
b

Parameter containing:
tensor([1.0000], requires_grad=True)